name: CI

on:
  pull_request:
  push:
    branches:
      - "*.*"
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
          - '8.2'
        symfony-version:
          - '5.4.*'
          - '6.4.*'
        coverage: [ 'none' ]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          tools: flex
          php-version: "${{ matrix.php-version }}"
          coverage: "${{ matrix.coverage }}"

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-version }}"

      - name: "Run tests"
        run: make phpunit
        env:
          PHP_IMAGE_TAG: "${{ matrix.php-version }}"
