name: CI

on:
  pull_request:
  push:
    branches:
      - "*.*"
      - master

jobs:
  tests:
    name: PHPUnit PHP ${{ matrix.php-version }} ${{ matrix.dependency }} (Symfony ${{ matrix.symfony-version }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'
        symfony-version:
          - '5.4.*'
          - '6.4.*'
        coverage: [ 'none' ]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: Configure Symfony
        run: composer config extra.symfony.require "${{ matrix.symfony-version }}"

      - name: Update project dependencies
        run: composer update --no-progress --ansi --prefer-stable

      - name: Validate composer
        run: composer validate --strict --no-check-lock

      - name: "Run code-style check"
        run: vendor/bin/php-cs-fixer fix --dry-run --config=.php-cs-fixer.dist.php --using-cache=no --show-progress=none -v

      - name: Run tests
        run: vendor/bin/phpunit
